yatube/about/urls.py
from django.urls import path

from about.views import AboutAuthorView, AboutTechView

app_name = 'about'

urlpatterns = [
    path('author/', AboutAuthorView.as_view(), name='author'),
    path('tech/', AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from posts.views import (
    group_posts,
    index,
    post_create,
    post_detail,
    post_edit,
    profile,
    add_comment,
    follow_index,
    profile_follow,
    profile_unfollow,
)

app_name = 'posts'

urlpatterns = [
    path('posts/<int:post_id>/edit/', post_edit, name='post_edit'),
    path('create/', post_create, name='post_create'),
    path('', index, name='index'),
    path('group/<slug:slug>/', group_posts, name='group_list'),
    path('profile/<str:username>/', profile, name='profile'),
    path('posts/<int:post_id>/', post_detail, name='post_detail'),
    path('posts/<int:post_id>/comment/', add_comment, name='add_comment'),
    path('follow/', follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        profile_unfollow,
        name='profile_unfollow',
    )
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path

from users.views import SignUp

app_name = 'users'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logged_out.html'),
        name='logout',
    ),
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html'),
        name='login',
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change',
    ),
    path(
        'reset/done',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complite.html'),
        name='password_reset_complite',
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm',
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done',
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change',
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form',
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/fields.html
<label for="{{ field.id_for_label }}">
  {{ field.label }}
  {% if field.field.required %}
    <span class="required text-danger" >*</span>
  {% endif %}
</label>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %} 
<nav class="navbar navbar-light" style="background-color: black">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span><span style="color:cyan">tube</span>
    </a>
    <ul class="nav nav-pills">
      <li class="nav-item"> 
        <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
          href="{% url 'about:author' %}"><span style="color:cyan">Об авторе</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
          href="{% url 'about:tech' %}"><span style="color:cyan">Технологии</span>
        </a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item"> 
        <a class="nav-link {% if view_name  == 'posts:post_create' or view_name  == 'posts:post_edit' %}active{% endif %}"
          href="{% url 'posts:post_create' %}"> <span style="color:yellow">Новая запись</span>
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == '' %}active{% endif %}"
          href="{% url 'users:password_change' %}"><span style="color:cyan">Изменить пароль</span>
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light"
          href="{% url 'users:logout' %}"><span style="color:red">Выйти</span>
        </a>
      </li>
      <li><a class="nav-link"><span style="color:cyan">Пользователь: </span><span style="color:red">{{ user.username }}</span></a>
      </li>
      {% else %}
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
          href="{% url 'users:login' %}">Войти
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
          href="{% url 'users:signup' %}">Регистрация
        </a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>      
{% endwith %} 