yatube/about/urls.py
from django.urls import path

from about.views import AboutAuthorView, AboutTechView

app_name = 'about'

urlpatterns = [
    path('author/', AboutAuthorView.as_view(), name='author'),
    path('tech/', AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from posts.views import (
    group_posts,
    index,
    post_create,
    post_detail,
    post_edit,
    profile,
    add_comment,
    follow_index,
    profile_follow,
    profile_unfollow,
)

app_name = 'posts'

urlpatterns = [
    path('posts/<int:post_id>/edit/', post_edit, name='post_edit'),
    path('create/', post_create, name='post_create'),
    path('', index, name='index'),
    path('group/<slug:slug>/', group_posts, name='group_list'),
    path('profile/<str:username>/', profile, name='profile'),
    path('posts/<int:post_id>/', post_detail, name='post_detail'),
    path('posts/<int:post_id>/comment/', add_comment, name='add_comment'),
    path('follow/', follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        profile_unfollow,
        name='profile_unfollow',
    )
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path

from users.views import SignUp

app_name = 'users'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logged_out.html'),
        name='logout',
    ),
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html'),
        name='login',
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change',
    ),
    path(
        'reset/done',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complite.html'),
        name='password_reset_complite',
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm',
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done',
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change',
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form',
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField("Название", max_length=200)
    slug = models.SlugField("Название группы", unique=True)
    description = models.TextField("Описание")

    class Meta:
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        help_text='Введите дату в формате ДД-ММ-ГГ',
        db_index=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста',
    )
    image = models.ImageField(
        'Картинка',
        help_text='Загрузите подходящую картинку',
        upload_to='posts/',
        blank=True,
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        related_name='posts',
        null=True,
        blank=True,
        help_text='Укажите группу для поста',
        verbose_name='Группа поста',
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор публикации',
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комменатрия'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчики'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Подписки'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_author_user_following',
            )
        ]

yatube/posts/forms.py
from django import forms

from posts.models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {
            'text': 'Новый пост',
            'group': 'Группа в которой будет находится пост',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Комментарий'}
        help_texts = {
            'text': 'Введите текст комментария'
        }

yatube/posts/views.py
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from posts.forms import CommentForm, PostForm
from posts.models import Group, Post, User, Follow


def paginator_function(posts, request):
    paginator = Paginator(posts, settings.MAX_RECORDS)
    page_number = request.GET.get("page")
    return paginator.get_page(page_number)


@cache_page(20 * 15)
def index(request):
    posts = Post.objects.all()
    page_obj = paginator_function(posts, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Display all posts group."""
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author')
    page_obj = paginator_function(posts, request)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    current_author = get_object_or_404(User, username=username)
    posts = current_author.posts.all()
    following = (request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=current_author).exists()
    )
    page_obj = paginator_function(posts, request)
    context = {
        'author': current_author,
        'page_obj': page_obj,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    posts = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = posts.comments.all()
    return render(
        request,
        'posts/post_detail.html',
        {'posts': posts, 'form': form, 'comments': comments}
    )


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.author = request.user
        obj.save()
        return redirect('posts:profile', obj.author)
    context = {
        'form': form,
        'is_edit': False}
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    edit_post = get_object_or_404(Post, pk=post_id)
    if request.user != edit_post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        instance=edit_post,
        files=request.FILES or None,
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    template = 'posts/create_post.html'
    context = {'form': form, 'is_edit': True}
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    posts = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = posts
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator_function(post_list, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=user, author=author)
    if user != author and not is_follower.exists():
        Follow.objects.create(user=user, author=author)
    return redirect(reverse('posts:profile', args=[username]))


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    if is_follower.exists():
        is_follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  {% if is_edit %}
    Редактирование поста
  {% else %}
    Создание поста
  {% endif %}
{% endblock title %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      {% include "includes/errors.html" %}
      <div class="card ">
        <div class="card-header">
          {% if is_edit %}
            <b>Редактировать пост</b>
          {% else %}
            <b>Добавить пост</b>
          {% endif %}
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                {% include "includes/fields.html" %}
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label}}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Добавить
                {% else %}
                  Сохранить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    {% include "posts/includes/switcher.html" %}
    {% load thumbnail %}
    {% for post in page_obj %}
      {% include "posts/includes/publication.html" %}
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}"><span style="color:red">все записи группы</span></a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    <div class="d-flex justify-content-center">
      <div>{% include "posts/includes/paginator.html" %}</div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Записи сообщества|{{ group.title }}{% endblock title %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description|linebreaksbr }}</p>
    <article>
      {% for post in page_obj %}
        {% include "posts/includes/post.html" %}
        {% if not forloop.last %}<hr>{% endif %}
      {% empty %}
        <h3>Отсутствуют записи. Поделитесь чем-нибудь!</h3>
      {% endfor %}
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
    </article>
  </div>
{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} Последние обновления на сайте{% endblock title %}
{% block content %}
  <div class="container py-5">
    {% include 'posts/includes/switcher.html' %}
    {% load cache %}
    <center><h2>Последние обновления на сайте. </h2></center>
    {% cache 20 index_page %}
      {% for post in page_obj %}
        <article>
          {% include "posts/includes/post.html" %}
          {% if post.group %}
            <b>Группа:</b> {{ group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}"><span style="color:red">Все записи группы.</span> </a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
      {% empty %}
        <h3>Отсутствуют записи. Поделитесь чем-нибудь!</h3>
        </article>
      {% endfor %}
      {% include "posts/includes/paginator.html" %}
    {% endcache %}
  </div>
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  Пост {{ posts|truncatechars:30 }}
{% endblock title %}
{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-2">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <center>
              <b>Дата публикации:</b>
            </center>
            <center>
              {{ posts.pub_date|date:"d E Y" }}
            </center>
          </li>
          {% if posts.group %}
            <li class="list-group-item">
              <center>
                <b>Группа: </b>
                {{ posts.group.title }}
                <a href="{% url 'posts:group_list' posts.group.slug %}"><center><span style="color:red">Все записи группы</span></center></a>
              </center>
          {% endif %}
        </li>
        <li class="list-group-item">
          <center>
            <b>Автор: </b>
          </center>
          <center>
            {{ post.author }}
            {{ posts.author.username }}
          </center>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <center>
            <b>Всего постов автора:
              {{ posts.author.posts.count }}</b>
          </center>
          {{ post_number }}
        </li>
        <center>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' posts.author.username %}"><span style="color:red">Все посты пользователя</span></a>
          </center>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail posts.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        <h5>{{ posts.text|linebreaksbr }}</h5>
      </p>
      {% if request.user == posts.author %}
        <a class="btn btn-primary"
          href="{% url 'posts:post_edit' posts.id %}">Редактировать</a>
      {% endif %}
      {% include "posts/includes/comment.html" %}
    </article>
  </div>
  </div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  {% if author.get_full_name %}
    {{ author.get_full_name }}
  {% else %}
    {{ author }}:
  {% endif %} Профиль  пользователя
{% endblock title %}
{% block content %}
  <div class="container py-5">
    <h1>Все посты пользователя
      {% if author.get_full_name %}{{ author.get_full_name }}
      {% else %}{{ author }}{% endif %}
    </h1>
    <h3>Всего постов:
      {{ page_obj.paginator.count }}
    </h3>
    {% if user.is_authenticated %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    {% else %}
      <a
        class="btn btn-lg btn-primary" href="{% url 'users:login' %}" role="button">
        Авторизуйтесь для подписки
      </a>
    {% endif %}
    {% for post in page_obj %}
      <div class="card my-3">
        <ul>
          <li>
            <b>Дата публикации:</b> {{ post.pub_date|date:'d E Y' }}
          </li>
        </ul>
      </div>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      <a href="{% url 'posts:post_detail' post.id %}"><span style="color:red">Подробная информация</span></a>
      <br>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}"><span style="color:red">Все записи группы</span></a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    <div class="d-flex justify-content-center">
      <div>{% include "posts/includes/paginator.html" %}</div>
    </div>
  </div>
{% endblock content %}